Repository opendr-eu/opendr, pull requests merged in 2021-12, with the labels that each got.

#157 Update references
  docs/reference/gem.md
  projects/perception/object_detection_2d/gem/inference_tutorial.ipynb
  src/opendr/perception/object_detection_2d/gem/README.md
Labels: documentation, test sources, test tools

#159 Landmark based facial expression recognition ros
  projects/opendr_ws/README.md
  projects/opendr_ws/src/perception/README.md
  projects/opendr_ws/src/perception/scripts/landmark_based_facial_expression_recognition.py
  projects/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/demo.py
  projects/perception/skeleton_based_action_recognition/REAMDE.md
  projects/perception/skeleton_based_action_recognition/demos/demo.py
  projects/perception/skeleton_based_action_recognition/demos/ntu60_labels.csv
  projects/perception/skeleton_based_action_recognition/demos/samples_with_missing_skeletons.txt
  projects/perception/skeleton_based_action_recognition/demos/skeleton_extraction.py
  src/opendr/perception/facial_expression_recognition/__init__.py
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/algorithm/datasets/AFEW_data_gen.py
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/algorithm/datasets/AFEW_labels.csv
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/algorithm/datasets/CASIA_CK_data_gen.py
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/algorithm/datasets/CASIA_labels.csv
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/algorithm/datasets/CK+_labels.csv
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/algorithm/datasets/landmark_extractor.py
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/dependencies.ini
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/progressive_spatio_temporal_bln_learner.py
Labels: test sources, test tools

#130 Skeleton based action recognition demo
  projects/perception/skeleton_based_action_recognition/REAMDE.md
  projects/perception/skeleton_based_action_recognition/demos/demo.py
  projects/perception/skeleton_based_action_recognition/demos/skeleton_extraction.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/models/pstgcn.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/models/stbln.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/models/stgcn.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/models/tagcn.py
Labels: test sources, test tools

#158 Skeleton based action recognition ros
  .github/workflows/tests_sources.yml
  projects/opendr_ws/README.md
  projects/opendr_ws/src/perception/README.md
  projects/opendr_ws/src/perception/scripts/skeleton_based_action_recognition.py
  projects/perception/skeleton_based_action_recognition/demos/demo.py
  src/opendr/perception/skeleton_based_action_recognition/__init__.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/datasets/kinetics400_classes.csv
  src/opendr/perception/skeleton_based_action_recognition/algorithm/datasets/kinetics_gendata.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/datasets/ntu60_labels.csv
  src/opendr/perception/skeleton_based_action_recognition/algorithm/datasets/ntu_gendata.py
  src/opendr/perception/skeleton_based_action_recognition/progressive_spatio_temporal_gcn_learner.py
  src/opendr/perception/skeleton_based_action_recognition/spatio_temporal_gcn_learner.py
Labels: test sources, test tools

#170 add demo readme
  projects/control/mobile_manipulation/README.md
Labels: documentation, test sources, test tools

#144 Add Hyperparameter Tuning
  docs/reference/hyperparameter_tuner.md
  docs/reference/index.md
  projects/utils/hyperparameter_tuner/hyperparameter_tuner_demo.py
  projects/utils/hyperparameter_tuner/hyperparameter_tuning_tutorial.ipynb
  src/opendr/engine/learners.py
  src/opendr/perception/object_detection_2d/detr/algorithm/engine.py
  src/opendr/perception/object_detection_2d/detr/algorithm/util/misc.py
  src/opendr/perception/object_detection_2d/detr/detr_learner.py
  src/opendr/utils/README.md
  src/opendr/utils/__init__.py
  src/opendr/utils/hyperparameter_tuner/README.md
  src/opendr/utils/hyperparameter_tuner/__init__.py
  src/opendr/utils/hyperparameter_tuner/dependencies.ini
  src/opendr/utils/hyperparameter_tuner/dummy_learner.py
  src/opendr/utils/hyperparameter_tuner/hyperparameter_tuner.py
  tests/sources/tools/utils/test_hyperparameter_tuner.py
Labels: test sources, test tools

#173 Move `mobile_manipulation` ws to projects
  docs/reference/mobile-manipulation.md
  src/opendr/control/mobile_manipulation/install_mobile_manipulation.sh
  tests/sources/tools/control/mobile_manipulation/run_ros.sh
Labels: enhancement, test sources, test tools

#175 ROS nodes for speech command recognition
  projects/opendr_ws/README.md
  projects/opendr_ws/src/perception/CMakeLists.txt
  projects/opendr_ws/src/perception/README.md
  projects/opendr_ws/src/perception/package.xml
  projects/opendr_ws/src/perception/scripts/speech_command_recognition.py
Labels: test sources, test tools

#178 tests are simplified
  .github/workflows/tests_sources.yml
  tests/sources/tools/perception/skeleton_based_action_recognition/test_pstgcn.py
  tests/sources/tools/perception/skeleton_based_action_recognition/test_stbln.py
  tests/sources/tools/perception/skeleton_based_action_recognition/test_stgcn.py
  tests/sources/tools/perception/skeleton_based_action_recognition/test_tagcn.py
Labels: test sources, test tools

#150 Smpl+d body models
  docs/reference/index.md
  docs/reference/smpld_models.md
  projects/simulation/SMPL+D_human_models/README.md
  projects/simulation/SMPL+D_human_models/examples/model_1.png
  projects/simulation/SMPL+D_human_models/examples/model_2.png
  projects/simulation/SMPL+D_human_models/examples/model_3.png
  projects/simulation/SMPL+D_human_models/examples/model_4.png
  projects/simulation/SMPL+D_human_models/src/download_data.py
  projects/simulation/SMPL+D_human_models/src/generate_models.py
  projects/simulation/SMPL+D_human_models/webots/extract_anims.py
  projects/simulation/SMPL+D_human_models/webots/install_project.sh
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/controllers/smpl_animation/Makefile
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/controllers/smpl_animation/smpl_animation.c
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/libraries/smpl_util/Makefile
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/libraries/smpl_util/include/quaternion_private.h
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/libraries/smpl_util/include/smpl_util.h
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/libraries/smpl_util/include/vector3_private.h
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/libraries/smpl_util/src/quaternion.c
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/libraries/smpl_util/src/smpl_util.c
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/libraries/smpl_util/src/vector3.c
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/protos/smpl_model_1.proto
  projects/simulation/SMPL+D_human_models/webots/smpl_webots/worlds/demo_world.wbt
  tests/test_license.py
Labels: test sources, test tools

#179 Add 3d detection and tracking ROS nodes
  docs/reference/rosbridge.md
  projects/opendr_ws/README.md
  projects/opendr_ws/src/perception/README.md
  projects/opendr_ws/src/perception/scripts/object_detection_3d_voxel.py
  projects/opendr_ws/src/perception/scripts/object_tracking_3d_ab3dmot.py
  projects/opendr_ws/src/perception/scripts/point_cloud_dataset.py
  projects/opendr_ws/src/ros_bridge/src/opendr_bridge/bridge.py
Labels: test sources, test tools

#183 Semantic segmentation demos
  projects/perception/semantic_segmentation/bisenet/README.md
  projects/perception/semantic_segmentation/bisenet/eval_demo.py
  projects/perception/semantic_segmentation/bisenet/inference_demo.py
  projects/perception/semantic_segmentation/bisenet/train_demo.py
Labels: test sources, test tools

#163 Add FairMOT and Deep Sort ROS nodes
  docs/reference/rosbridge.md
  projects/opendr_ws/README.md
  projects/opendr_ws/src/perception/README.md
  projects/opendr_ws/src/perception/scripts/image_dataset.py
  projects/opendr_ws/src/perception/scripts/object_tracking_2d_deep_sort.py
  projects/opendr_ws/src/perception/scripts/object_tracking_2d_fair_mot.py
  projects/opendr_ws/src/ros_bridge/src/opendr_bridge/bridge.py
  src/opendr/engine/data.py
  src/opendr/perception/object_tracking_2d/deep_sort/algorithm/deep_sort/deep_sort.py
  src/opendr/perception/object_tracking_2d/fair_mot/object_tracking_2d_fair_mot_learner.py
Labels: test sources, test tools

#186 Semantic segmentation documentation update
  docs/reference/semantic-segmentation.md
Labels: test sources, test tools

#185 Αdded documentation for object detectors + cpu/gpu switching
  docs/reference/face-detection-2d-retinaface.md
  docs/reference/object-detection-2d-centernet.md
  docs/reference/object-detection-2d-ssd.md
  docs/reference/object-detection-2d-yolov3.md
  src/opendr/perception/object_detection_2d/retinaface/retinaface_learner.py
Labels: test sources, test tools

#187 ROS nodes for speech command recognition, extension
  projects/opendr_ws/src/perception/README.md
  projects/opendr_ws/src/perception/scripts/speech_command_recognition.py
Labels: test sources, test tools

#189 Update human-model-generation.md
  docs/reference/human-model-generation.md
Labels: documentation, test sources, test tools

#182 Update index.md
  docs/reference/activity-recognition.md
  docs/reference/attention-neural-bag-of-feature-learner.md
  docs/reference/detr.md
  docs/reference/edgespeechnets.md
  docs/reference/efficient-ps.md
  docs/reference/engine-data.md
  docs/reference/engine-datasets.md
  docs/reference/engine-target.md
  docs/reference/face-detection-2d-retinaface.md
  docs/reference/face-recognition.md
  docs/reference/gated-recurrent-unit-learner.md
  docs/reference/gem.md
  docs/reference/human-model-generation.md
  docs/reference/index.md
  docs/reference/inference-and-training-api.md
  docs/reference/landmark-based-facial-expression-recognition.md
  docs/reference/lightweight-open-pose.md
  docs/reference/matchboxnet.md
  docs/reference/mobile-manipulation.md
  docs/reference/multilinear-compressive-learning.md
  docs/reference/object-detection-2d-centernet.md
  docs/reference/object-detection-2d-ssd.md
  docs/reference/object-detection-2d-yolov3.md
  docs/reference/object-tracking-2d-deep-sort.md
  docs/reference/object-tracking-2d-fair-mot.md
  docs/reference/object-tracking-3d-ab3dmot.md
  docs/reference/quadratic-selfonn.md
  docs/reference/rgbd-hand-gesture-learner.md
  docs/reference/semantic-segmentation.md
  docs/reference/single-demonstration-grasping.md
  docs/reference/skeleton-based-action-recognition.md
  docs/reference/voxel-object-detection-3d.md
  projects/control/mobile_manipulation/README.md
  projects/perception/lightweight_open_pose/jetbot/README.md
Labels: test sources, test tools

#188 Missing demo for speech command recognition
  projects/perception/speech_command_recognition/README.MD
  projects/perception/speech_command_recognition/demo.py
  projects/perception/speech_command_recognition/example1.wav
  projects/perception/speech_command_recognition/example2.wav
Labels: test sources, test tools
