Repository opendr-eu/opendr, pull requests merged in 2021-07, with the labels that each got.

#58 Speech command recognition - MatchboxNet
  docs/reference/matchboxnet.md
  src/opendr/perception/speech_recognition/matchboxnet/README.md
  src/opendr/perception/speech_recognition/matchboxnet/__init__.py
  src/opendr/perception/speech_recognition/matchboxnet/algorithm/__init__.py
  src/opendr/perception/speech_recognition/matchboxnet/algorithm/audioutils.py
  src/opendr/perception/speech_recognition/matchboxnet/algorithm/model.py
  src/opendr/perception/speech_recognition/matchboxnet/dependencies.ini
  src/opendr/perception/speech_recognition/matchboxnet/matchboxnet_learner.py
  tests/sources/tools/perception/speech_recognition/matchboxnet/__init__.py
  tests/sources/tools/perception/speech_recognition/matchboxnet/test_matchboxnet.py
Labels: enhancement, test sources, test tools

#85 Add online activity recognition demo
  projects/perception/activity_recognition/demos/online_recognition/README.md
  projects/perception/activity_recognition/demos/online_recognition/activity_recognition/__init__.py
  projects/perception/activity_recognition/demos/online_recognition/activity_recognition/kinetics400_classes.csv
  projects/perception/activity_recognition/demos/online_recognition/activity_recognition/screenshot.png
  projects/perception/activity_recognition/demos/online_recognition/activity_recognition/video.gif
  projects/perception/activity_recognition/demos/online_recognition/demo.py
  projects/perception/activity_recognition/demos/online_recognition/requirements.txt
  projects/perception/activity_recognition/demos/online_recognition/setup.py
  projects/perception/activity_recognition/demos/online_recognition/templates/index.html
Labels: enhancement, test sources

#105 Fix issue 103
  tests/sources/tools/perception/activity_recognition/cox3d/test_cox3d_learner.py
  tests/sources/tools/perception/activity_recognition/x3d/test_x3d_learner.py
Labels: bug, test sources, test tools

#97 Development notice in README.md
  README.md
Labels: documentation, test sources, test tools

#88 Fix EdgeSpeechNets target class and test
  docs/reference/engine-target.md
  src/opendr/engine/target.py
  src/opendr/perception/speech_recognition/edgespeechnets/edgespeechnets_learner.py
  tests/sources/tools/perception/speech_recognition/edgespeechnets/test_edgespeechnets.py
Labels: test sources, test tools

#104 Pose estimation NumPy compatibility fixes
  src/opendr/perception/pose_estimation/dependencies.ini
Labels: enhancement, test sources, test tools

#98 Data and Target setter/getter fixes
  docs/reference/engine-target.md
  src/opendr/engine/data.py
  src/opendr/engine/target.py
Labels: bug, enhancement, test sources, test tools
