Repository opendr-eu/opendr, pull requests merged in 2022-03, with the labels that each got.

#236 Synchronize master and develop workflows
  .github/workflows/tests_suite.yml
  .github/workflows/tests_suite_develop.yml
Labels: enhancement, test sources

#238 Added OpenDR citation
  README.md
Labels: test sources, test tools

#241 Citation bibtex name fix
  README.md
Labels: test sources, test tools

#242 Lightweight openpose fixes
  CHANGELOG.md
  src/opendr/perception/pose_estimation/lightweight_open_pose/algorithm/datasets/transformations.py
  src/opendr/perception/pose_estimation/lightweight_open_pose/lightweight_open_pose_learner.py
Labels: bug, test sources, test tools
