Repository opendr-eu/opendr, pull requests merged in 2022-05, with the labels that each got.

#253 Update CODEOWNERS
  CODEOWNERS
Labels: test sources

#247 Added webcam demo for Face Recognition
  projects/perception/face_recognition/README.md
  projects/perception/face_recognition/demos/webcam_demo.py
Labels: enhancement, test sources

#232 Nms module
  .github/workflows/test_packages.yml
  .github/workflows/tests_suite.yml
  .github/workflows/tests_suite_develop.yml
  CHANGELOG.md
  docs/reference/index.md
  docs/reference/object-detection-2d-nms-seq2seq_nms.md
  projects/opendr_ws/src/perception/scripts/object_detection_2d_ssd.py
  projects/perception/object_detection_2d/nms/cluster_nms/README.md
  projects/perception/object_detection_2d/nms/cluster_nms/inference_demo.py
  projects/perception/object_detection_2d/nms/fast_nms/README.md
  projects/perception/object_detection_2d/nms/fast_nms/inference_demo.py
  projects/perception/object_detection_2d/nms/img_temp/frame_0000.jpg
  projects/perception/object_detection_2d/nms/seq2seq-nms/README.md
  projects/perception/object_detection_2d/nms/seq2seq-nms/eval_demo.py
  projects/perception/object_detection_2d/nms/seq2seq-nms/inference_demo.py
  projects/perception/object_detection_2d/nms/seq2seq-nms/train_demo.py
  projects/perception/object_detection_2d/nms/soft_nms/README.md
  projects/perception/object_detection_2d/nms/soft_nms/inference_demo.py
  src/opendr/perception/object_detection_2d/__init__.py
  src/opendr/perception/object_detection_2d/datasets/transforms.py
  src/opendr/perception/object_detection_2d/dependencies.ini
  src/opendr/perception/object_detection_2d/nms/__init__.py
  src/opendr/perception/object_detection_2d/nms/cluster_nms/README.md
  src/opendr/perception/object_detection_2d/nms/cluster_nms/__init__.py
  src/opendr/perception/object_detection_2d/nms/cluster_nms/cluster_nms.py
  src/opendr/perception/object_detection_2d/nms/fast_nms/README.md
  src/opendr/perception/object_detection_2d/nms/fast_nms/__init__.py
  src/opendr/perception/object_detection_2d/nms/fast_nms/fast_nms.py
  src/opendr/perception/object_detection_2d/nms/seq2seq_nms/README.md
  src/opendr/perception/object_detection_2d/nms/seq2seq_nms/__init__.py
  src/opendr/perception/object_detection_2d/nms/seq2seq_nms/algorithm/fmod.py
  src/opendr/perception/object_detection_2d/nms/seq2seq_nms/algorithm/seq2seq_model.py
  src/opendr/perception/object_detection_2d/nms/seq2seq_nms/seq2seq_nms_learner.py
  src/opendr/perception/object_detection_2d/nms/soft_nms/README.md
  src/opendr/perception/object_detection_2d/nms/soft_nms/__init__.py
  src/opendr/perception/object_detection_2d/nms/soft_nms/soft_nms.py
  src/opendr/perception/object_detection_2d/nms/utils/__init__.py
  src/opendr/perception/object_detection_2d/nms/utils/nms_custom.py
  src/opendr/perception/object_detection_2d/nms/utils/nms_dataset.py
  src/opendr/perception/object_detection_2d/nms/utils/nms_utils.py
  src/opendr/perception/object_detection_2d/ssd/ssd_learner.py
  tests/sources/tools/perception/object_detection_2d/nms/__init__.py
  tests/sources/tools/perception/object_detection_2d/nms/seq2seq_nms/__init__.py
  tests/sources/tools/perception/object_detection_2d/nms/seq2seq_nms/test_seq2seq_nms.py
Labels: test sources, test tools

#257 Update face-recognition.md
  docs/reference/face-recognition.md
Labels: test sources
