Repository opendr-eu/opendr, pull requests merged in 2022-08, with the labels that each got.

#285 Object detection 2d auth evalfix
  src/opendr/perception/object_detection_2d/utils/eval_utils.py
Labels: test sources, test tools

#280 Clarified purpose and limitations of fall detection tool in docs
  docs/reference/fall-detection.md
Labels: documentation, test sources

#279 Add ROS2 face recognition and fall detection nodes
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/face_detection_retinaface_node.py
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/face_recognition_node.py
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/fall_detection_node.py
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/object_detection_2d_detr_node.py
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/object_detection_2d_ssd_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
  projects/opendr_ws_2/src/opendr_ros2_bridge/opendr_ros2_bridge/bridge.py
Labels: enhancement, test sources, test tools

#289 Citation Update
  README.md
Labels: test sources
