Repository opendr-eu/opendr, pull requests merged in 2022-06, with the labels that each got.

#260 skeleton-based HAR demo bug fixed
  projects/perception/skeleton_based_action_recognition/demos/demo.py
  src/c_api/face_recognition.cpp
  src/opendr/perception/skeleton_based_action_recognition/progressive_spatio_temporal_gcn_learner.py
  src/opendr/perception/skeleton_based_action_recognition/spatio_temporal_gcn_learner.py
Labels: test sources

#261 Merge `master`into `develop`
  .github/workflows/tests_suite_develop.yml
  Dockerfile-cuda
  docs/reference/face-recognition.md
  projects/perception/skeleton_based_action_recognition/demos/demo.py
  src/c_api/face_recognition.cpp
  src/opendr/perception/object_detection_2d/nms/seq2seq_nms/algorithm/__init__.py
  src/opendr/perception/skeleton_based_action_recognition/progressive_spatio_temporal_gcn_learner.py
  src/opendr/perception/skeleton_based_action_recognition/spatio_temporal_gcn_learner.py
Labels: test sources, test tools, test release, synchronization

#263 Prepare 1.1.0
  CHANGELOG.md
  projects/opendr_ws/src/data_generation/package.xml
  projects/opendr_ws/src/perception/package.xml
  projects/opendr_ws/src/ros_bridge/package.xml
  projects/opendr_ws/src/simulation/package.xml
  projects/perception/slam/full_map_posterior_gmapping/src/fmp_slam_eval/package.xml
  projects/perception/slam/full_map_posterior_gmapping/src/map_simulator/package.xml
  src/opendr/_version.py
Labels: test sources

#267 Fix face recognition
  src/c_api/face_recognition.cpp
Labels: test sources, test tools

#266 Cleanup GitHub workflows
  .github/workflows/test_packages.yml
  .github/workflows/tests_suite.yml
  .github/workflows/tests_suite_develop.yml
Labels: test sources

#274 Prepare 1.1.1
  CHANGELOG.md
  projects/opendr_ws/src/data_generation/package.xml
  projects/opendr_ws/src/perception/package.xml
  projects/opendr_ws/src/ros_bridge/package.xml
  projects/opendr_ws/src/simulation/package.xml
  projects/perception/slam/full_map_posterior_gmapping/src/fmp_slam_eval/package.xml
  projects/perception/slam/full_map_posterior_gmapping/src/map_simulator/package.xml
  src/opendr/_version.py
Labels: test sources, test tools, test release
