Repository opendr-eu/opendr, pull requests merged in 2022-09, with the labels that each got.

#290 Merge master into develop branch
  .github/workflows/test_packages.yml
  .github/workflows/tests_suite.yml
  .github/workflows/tests_suite_develop.yml
  CHANGELOG.md
  bin/install.sh
  docs/reference/installation.md
  projects/data_generation/synthetic_multi_view_facial_image_generation/requirements.txt
  projects/opendr_ws/src/data_generation/package.xml
  projects/opendr_ws/src/perception/package.xml
  projects/opendr_ws/src/ros_bridge/package.xml
  projects/opendr_ws/src/simulation/package.xml
  projects/perception/slam/full_map_posterior_gmapping/src/fmp_slam_eval/package.xml
  projects/perception/slam/full_map_posterior_gmapping/src/map_simulator/package.xml
  src/c_api/face_recognition.cpp
  src/opendr/_version.py
  src/opendr/control/single_demo_grasp/Makefile
  src/opendr/control/single_demo_grasp/dependencies.ini
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/dependencies.ini
  src/opendr/simulation/human_model_generation/dependencies.ini
  src/opendr/simulation/human_model_generation/utilities/PIFu/lib/mesh_util.py
Labels: test sources, test tools, test release, synchronization

#281 ROS1 updates and fixes for several nodes
  docs/reference/rosbridge.md
  projects/opendr_ws/src/perception/README.md
  projects/opendr_ws/src/perception/scripts/face_detection_retinaface.py
  projects/opendr_ws/src/perception/scripts/face_recognition.py
  projects/opendr_ws/src/perception/scripts/fall_detection.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_detr.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_ssd.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_yolov3.py
  projects/opendr_ws/src/perception/scripts/pose_estimation.py
  projects/opendr_ws/src/perception/scripts/semantic_segmentation_bisenet.py
  projects/opendr_ws/src/ros_bridge/CMakeLists.txt
  projects/opendr_ws/src/ros_bridge/msg/.keep
  projects/opendr_ws/src/ros_bridge/msg/OpenDRPose2D.msg
  projects/opendr_ws/src/ros_bridge/msg/OpenDRPose2DKeypoint.msg
  projects/opendr_ws/src/ros_bridge/src/opendr_bridge/bridge.py
  projects/opendr_ws/src/simulation/scripts/human_model_generation_client.py
  src/opendr/engine/target.py
Labels: test sources, test tools

#269 Panoptic segmentation: download pretrained weights in ROS node
  projects/opendr_ws/src/perception/README.md
  projects/opendr_ws/src/perception/scripts/panoptic_segmentation_efficient_ps.py
  src/opendr/engine/target.py
  src/opendr/perception/panoptic_segmentation/efficient_ps/efficient_ps_learner.py
Labels: test sources, test tools

#207 Fix 3D Detection And 2D Tracking Tests
  .github/workflows/test_packages.yml
  bin/install.sh
  src/opendr/perception/object_detection_2d/utils/eval_utils.py
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/dependencies.ini
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/second_detector/configs/pointpillars/car/test_short.proto
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/second_detector/configs/tanet/car/test_short.proto
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/second_detector/core/geometry.py
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/voxel_object_detection_3d_learner.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/gen_labels_mot.py
  tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/test_object_detection_3d.py
  tests/sources/tools/perception/object_tracking_2d/__init__.py
Labels: test sources, test release

#297 Merge `master` branch into `develop` branch
  .github/workflows/test_packages.yml
  Dockerfile-cuda
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/dependencies.ini
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/second_detector/configs/pointpillars/car/test_short.proto
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/second_detector/configs/tanet/car/test_short.proto
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/second_detector/core/geometry.py
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/voxel_object_detection_3d_learner.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/gen_labels_mot.py
  tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/test_object_detection_3d.py
  tests/sources/tools/perception/object_tracking_2d/__init__.py
Labels: test sources, test release

#300 Fix ROS1 bridge type conversion bug
  projects/opendr_ws/src/ros_bridge/src/opendr_bridge/bridge.py
  src/opendr/perception/object_detection_2d/yolov3/yolov3_learner.py
Labels: bug, test sources, test tools

#306 ROS1 nodes - None argument fix
  projects/opendr_ws/src/perception/scripts/face_detection_retinaface.py
  projects/opendr_ws/src/perception/scripts/face_recognition.py
  projects/opendr_ws/src/perception/scripts/fall_detection.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_centernet.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_ssd.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_yolov3.py
  projects/opendr_ws/src/perception/scripts/pose_estimation.py
  projects/opendr_ws/src/perception/scripts/semantic_segmentation_bisenet.py
Labels: bug, test sources, test tools

#311 Fix cppcheck 2.9 errors
  src/c_api/face_recognition.cpp
Labels: test sources

#312 merge `master` into `develop`
  src/c_api/face_recognition.cpp
Labels: test sources

#310 Customize.md - fixes on broken and wrong links
  docs/reference/customize.md
Labels: documentation, test sources

#296 Ros2 detr
  projects/opendr_ws/src/perception/scripts/object_detection_2d_detr.py
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/object_detection_2d_detr_node.py
Labels: enhancement, test sources

#298 Docker scheduled tests update
  .github/workflows/test_packages.yml
  docs/reference/installation.md
Labels: test sources, test packages

#315 Fix import instructions in RetinaFaceLearner documentation
  docs/reference/face-detection-2d-retinaface.md
Labels: documentation, test sources

#322 Fix ros1 video_activity_recognition.py
  projects/opendr_ws/src/perception/scripts/video_activity_recognition.py
Labels: test sources
