Repository opendr-eu/opendr, pull requests merged in 2022-10, with the labels that each got.

#323 Ros2 har
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/video_activity_recognition_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
  projects/opendr_ws_2/src/opendr_ros2_bridge/opendr_ros2_bridge/bridge.py
Labels: test sources

#327 Update documentation version
  docs/reference/index.md
Labels: test sources

#318 merge `master` into `develop`
  .github/workflows/test_packages.yml
  docs/reference/face-detection-2d-retinaface.md
  docs/reference/installation.md
Labels: test sources

#325 Ros1 fixed rgbd hand gestures recognition
  projects/opendr_ws/src/perception/scripts/rgbd_hand_gesture_recognition.py
Labels: test sources

#331 Ros1 fixes speech command recognition
  projects/opendr_ws/src/perception/scripts/speech_command_recognition.py
Labels: test sources

#330 Ros1 fixes heart anomaly detection
  projects/opendr_ws/src/perception/scripts/heart_anomaly_detection.py
Labels: test sources

#332 Ros1 fixes audiovisual emotion recognition
  projects/opendr_ws/src/perception/scripts/audiovisual_emotion_recognition.py
Labels: test sources

#336 Ros1 fixes early create subscribers
  projects/opendr_ws/src/perception/scripts/heart_anomaly_detection.py
  projects/opendr_ws/src/perception/scripts/rgbd_hand_gesture_recognition.py
Labels: test sources

#339 Update heart_anomaly_detection.py
  projects/opendr_ws/src/perception/scripts/heart_anomaly_detection.py
Labels: test sources

#341 ROS2 RGBD hand gestures recognition
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/rgbd_hand_gesture_recognition_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
  projects/opendr_ws_2/src/opendr_ros2_bridge/opendr_ros2_bridge/bridge.py
Labels: test sources

#291 ROS2 implementation for human_model_generation module
  projects/opendr_ws_2/src/opendr_ros2_bridge/opendr_ros2_bridge/bridge.py
  projects/opendr_ws_2/src/opendr_ros2_messages/CMakeLists.txt
  projects/opendr_ws_2/src/opendr_ros2_messages/msg/OpenDRPose3D.msg
  projects/opendr_ws_2/src/opendr_ros2_messages/msg/OpenDRPose3DKeypoint.msg
  projects/opendr_ws_2/src/opendr_ros2_messages/srv/ImgToMesh.srv
  projects/opendr_ws_2/src/opendr_simulation/opendr_simulation/__init__.py
  projects/opendr_ws_2/src/opendr_simulation/opendr_simulation/human_model_generation_client.py
  projects/opendr_ws_2/src/opendr_simulation/opendr_simulation/human_model_generation_service.py
  projects/opendr_ws_2/src/opendr_simulation/package.xml
  projects/opendr_ws_2/src/opendr_simulation/resource/opendr_simulation
  projects/opendr_ws_2/src/opendr_simulation/setup.cfg
  projects/opendr_ws_2/src/opendr_simulation/setup.py
  projects/opendr_ws_2/src/opendr_simulation/test/test_copyright.py
  projects/opendr_ws_2/src/opendr_simulation/test/test_flake8.py
  projects/opendr_ws_2/src/opendr_simulation/test/test_pep257.py
  src/opendr/simulation/human_model_generation/dependencies.ini
  src/opendr/simulation/human_model_generation/utilities/PIFu/lib/mesh_util.py
  tests/test_license.py
Labels: enhancement, test sources, test tools

#270 Add ROS2 node for EfficientPS
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/panoptic_segmentation_efficient_ps.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
Labels: enhancement, test sources, test tools

#337 ROS2 for heart anomaly detection
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/heart_anomaly_detection_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
  projects/opendr_ws_2/src/opendr_ros2_bridge/opendr_ros2_bridge/bridge.py
Labels: test sources

#340 ROS2 speech command recognition
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/speech_command_recognition_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
Labels: test sources

#342 ROS2 for audiovisual emotion recognition node
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/audiovisual_emotion_recognition_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
Labels: test sources

#344 Skeleton_based_action_recognition ROS2 node
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/skeleton_based_action_recognition_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
Labels: test sources

#326 Update har onnx inference and benchmark scripts
  projects/python/perception/activity_recognition/benchmark/benchmark_cox3d.py
  projects/python/perception/activity_recognition/benchmark/benchmark_x3d.py
  src/opendr/perception/activity_recognition/cox3d/cox3d_learner.py
  src/opendr/perception/activity_recognition/x3d/x3d_learner.py
Labels: test sources, test tools

#345 landmark_based_facial_expression_recognition ROS2 node
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/landmark_based_facial_expression_recognition_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
Labels: test sources

#307 ros1_node for landmark_expression_recognition updated
  projects/opendr_ws/src/perception/scripts/landmark_based_facial_expression_recognition.py
Labels: test sources

#343 ROS1 fixes for no output for RGBD hand gesture recognition
  docs/reference/images/hand_gesture_examples.png
  docs/reference/rgbd-hand-gesture-learner.md
  projects/opendr_ws/src/perception/scripts/rgbd_hand_gesture_recognition.py
Labels: test sources

#308 Har ros1 fix
  projects/opendr_ws/src/perception/scripts/audiovisual_emotion_recognition.py
  projects/opendr_ws/src/perception/scripts/fall_detection.py
  projects/opendr_ws/src/perception/scripts/image_dataset.py
  projects/opendr_ws/src/perception/scripts/landmark_based_facial_expression_recognition.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_detr.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_gem.py
  projects/opendr_ws/src/perception/scripts/object_detection_2d_nanodet.py
  projects/opendr_ws/src/perception/scripts/object_detection_3d_voxel.py
  projects/opendr_ws/src/perception/scripts/object_tracking_2d_deep_sort.py
  projects/opendr_ws/src/perception/scripts/object_tracking_3d_ab3dmot.py
  projects/opendr_ws/src/perception/scripts/point_cloud_dataset.py
  projects/opendr_ws/src/perception/scripts/pose_estimation.py
  projects/opendr_ws/src/perception/scripts/semantic_segmentation_bisenet.py
  projects/opendr_ws/src/perception/scripts/skeleton_based_action_recognition.py
  projects/python/perception/skeleton_based_action_recognition/demos/demo.py
  projects/python/perception/skeleton_based_action_recognition/demos/skeleton_extraction.py
Labels: test sources
