Repository opendr-eu/opendr, pull requests merged in 2022-12, with the labels that each got.

#348 Allow to not use a pretrained FairMOT backbone
  projects/python/perception/object_tracking_2d/demos/fair_mot_deep_sort/demo.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/lib/models/model.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/lib/models/networks/dlav0.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/lib/models/networks/pose_dla_conv.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/lib/models/networks/pose_dla_dcn.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/lib/models/networks/pose_hrnet.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/lib/models/networks/resnet_dcn.py
  src/opendr/perception/object_tracking_2d/fair_mot/algorithm/lib/models/networks/resnet_fpn_dcn.py
  src/opendr/perception/object_tracking_2d/fair_mot/object_tracking_2d_fair_mot_learner.py
  tests/sources/tools/perception/object_tracking_2d/fair_mot/test_object_tracking_2d_fair_mot.py
Labels: test sources, test tools

#364 ROS1 final updates
  dependencies/pip_requirements.txt
  docs/reference/customize.md
  docs/reference/index.md
  docs/reference/issues.md
  docs/reference/opendr-ros-bridge.md
  projects/opendr_ws/src/data_generation/README.md
  projects/opendr_ws/src/opendr_bridge/CMakeLists.txt
  projects/opendr_ws/src/opendr_bridge/include/opendr_bridge/.keep
  projects/opendr_ws/src/opendr_bridge/msg/OpenDRPose2D.msg
  projects/opendr_ws/src/opendr_bridge/msg/OpenDRPose2DKeypoint.msg
  projects/opendr_ws/src/opendr_bridge/package.xml
  projects/opendr_ws/src/opendr_bridge/setup.py
  projects/opendr_ws/src/opendr_bridge/src/opendr_bridge/__init__.py
  projects/opendr_ws/src/opendr_bridge/src/opendr_bridge/bridge.py
  projects/opendr_ws/src/opendr_data_generation/CMakeLists.txt
  projects/opendr_ws/src/opendr_data_generation/README.md
  projects/opendr_ws/src/opendr_data_generation/package.xml
  projects/opendr_ws/src/opendr_data_generation/scripts/synthetic_facial_generation_node.py
  projects/opendr_ws/src/opendr_perception/CMakeLists.txt
  projects/opendr_ws/src/opendr_perception/README.md
  projects/opendr_ws/src/opendr_perception/include/opendr_perception/.keep
  projects/opendr_ws/src/opendr_perception/package.xml
  projects/opendr_ws/src/opendr_perception/scripts/audiovisual_emotion_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/face_detection_retinaface_node.py
  projects/opendr_ws/src/opendr_perception/scripts/face_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/fall_detection_node.py
  projects/opendr_ws/src/opendr_perception/scripts/heart_anomaly_detection_node.py
  projects/opendr_ws/src/opendr_perception/scripts/image_dataset_node.py
  projects/opendr_ws/src/opendr_perception/scripts/landmark_based_facial_expression_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_centernet_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_detr_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_gem_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_nanodet_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_ssd_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_yolov3_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_yolov5_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_3d_voxel_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_2d_deep_sort_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_2d_fair_mot_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_3d_ab3dmot_node.py
  projects/opendr_ws/src/opendr_perception/scripts/panoptic_segmentation_efficient_ps_node.py
  projects/opendr_ws/src/opendr_perception/scripts/point_cloud_dataset_node.py
  projects/opendr_ws/src/opendr_perception/scripts/pose_estimation_node.py
  projects/opendr_ws/src/opendr_perception/scripts/rgbd_hand_gesture_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/semantic_segmentation_bisenet_node.py
  projects/opendr_ws/src/opendr_perception/scripts/skeleton_based_action_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/speech_command_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/video_activity_recognition_node.py
  projects/opendr_ws/src/opendr_perception/src/.keep
  projects/opendr_ws/src/opendr_planning/CMakeLists.txt
  projects/opendr_ws/src/opendr_planning/include/opendr_planning/.keep
  projects/opendr_ws/src/opendr_planning/package.xml
  projects/opendr_ws/src/opendr_planning/scripts/end_to_end_planner_node.py
  projects/opendr_ws/src/opendr_planning/src/.keep
  projects/opendr_ws/src/opendr_simulation/CMakeLists.txt
  projects/opendr_ws/src/opendr_simulation/README.md
  projects/opendr_ws/src/opendr_simulation/package.xml
  projects/opendr_ws/src/opendr_simulation/scripts/human_model_generation_client.py
  projects/opendr_ws/src/opendr_simulation/scripts/human_model_generation_service.py
  projects/opendr_ws/src/opendr_simulation/srv/Mesh_vc.srv
Labels: test sources, test tools

#355 Merge `master` into `develop`
  docs/reference/index.md
  projects/python/control/eagerx/dependencies.ini
  projects/python/simulation/SMPL+D_human_models/src/download_data.py
  src/opendr/perception/object_detection_2d/dependencies.ini
Labels: test sources, test tools

#317 Continual Transformer Encoder
  CHANGELOG.md
  docs/reference/activity-recognition.md
  docs/reference/continual-transformer-encoder.md
  docs/reference/index.md
  projects/python/perception/activity_recognition/benchmark/README.md
  projects/python/perception/activity_recognition/benchmark/benchmark_cotransenc.py
  projects/python/perception/activity_recognition/demos/continual_transformer_encoder/README.md
  projects/python/perception/activity_recognition/demos/continual_transformer_encoder/demo.py
  src/opendr/perception/activity_recognition/README.md
  src/opendr/perception/activity_recognition/__init__.py
  src/opendr/perception/activity_recognition/continual_transformer_encoder/__init__.py
  src/opendr/perception/activity_recognition/continual_transformer_encoder/continual_transformer_encoder_learner.py
  src/opendr/perception/activity_recognition/datasets/__init__.py
  src/opendr/perception/activity_recognition/datasets/dummy_timeseries_dataset.py
  src/opendr/perception/activity_recognition/dependencies.ini
  src/opendr/utils/hyperparameter_tuner/dependencies.ini
  tests/sources/tools/perception/activity_recognition/continual_transformer_encoder/__init__.py
  tests/sources/tools/perception/activity_recognition/continual_transformer_encoder/test_continual_transformer_encoder_learner.py
Labels: enhancement, test sources, test tools

#365 Fix bbox/tracking 2D/3D list confidence
  CHANGELOG.md
  src/opendr/engine/target.py
Labels: test sources, test tools

#361 Ambiguity measure
  CHANGELOG.md
  docs/reference/ambiguity_measure.md
  docs/reference/index.md
  packages.txt
  projects/python/utils/ambiguity_measure/ambiguity_measure_tutorial.ipynb
  src/opendr/utils/README.md
  src/opendr/utils/ambiguity_measure/README.md
  src/opendr/utils/ambiguity_measure/__init__.py
  src/opendr/utils/ambiguity_measure/ambiguity_measure.py
  src/opendr/utils/ambiguity_measure/dependencies.ini
  src/opendr/utils/ambiguity_measure/persistence.py
  tests/sources/tools/utils/test_ambiguity_measure.py
Labels: test sources, test tools

#316 ROS1 documentation updates and enhancements
  bin/install.sh
  docs/reference/activity-recognition.md
  docs/reference/semantic-segmentation.md
  projects/opendr_ws/README.md
  projects/opendr_ws/images/opendr_node_diagram.png
  projects/opendr_ws/src/opendr_perception/README.md
Labels: documentation, test sources

#338 Demo 3D tracking
  projects/python/perception/object_detection_3d/demos/voxel_object_detection_3d/README.md
  projects/python/perception/object_detection_3d/demos/voxel_object_detection_3d/demo.py
  src/opendr/perception/object_tracking_3d/ab3dmot/algorithm/ab3dmot.py
  src/opendr/perception/object_tracking_3d/ab3dmot/algorithm/core.py
  src/opendr/perception/object_tracking_3d/ab3dmot/algorithm/evaluate.py
  src/opendr/perception/object_tracking_3d/ab3dmot/algorithm/kalman_tracker_3d.py
  src/opendr/perception/object_tracking_3d/ab3dmot/object_tracking_3d_ab3dmot_learner.py
  src/opendr/perception/object_tracking_3d/datasets/kitti_tracking.py
  tests/sources/tools/perception/object_tracking_3d/ab3dmot/test_object_tracking_3d_ab3dmot.py
Labels: test sources, test tools

#376 Improve installation script and docs
  bin/install.sh
  docs/reference/installation.md
  projects/opendr_ws/README.md
  projects/opendr_ws/src/opendr_perception/README.md
Labels: test sources, test tools

#375 Fix nightly tests in CI
  .github/workflows/tests_suite.yml
  .github/workflows/tests_suite_develop.yml
  Dockerfile
  src/opendr/perception/object_detection_2d/dependencies.ini
Labels: bug, test sources, test release

#372 Fix cox3d_learner ONNX support
  CHANGELOG.md
  src/opendr/perception/activity_recognition/cox3d/algorithm/conv.py
  src/opendr/perception/activity_recognition/cox3d/algorithm/cox3d.py
  src/opendr/perception/activity_recognition/cox3d/algorithm/delay.py
  src/opendr/perception/activity_recognition/cox3d/algorithm/pooling.py
  src/opendr/perception/activity_recognition/cox3d/algorithm/res.py
  src/opendr/perception/activity_recognition/cox3d/algorithm/se.py
  src/opendr/perception/activity_recognition/cox3d/algorithm/utils.py
  src/opendr/perception/activity_recognition/cox3d/algorithm/x3d.py
  src/opendr/perception/activity_recognition/cox3d/cox3d_learner.py
  src/opendr/perception/activity_recognition/datasets/kinetics.py
  src/opendr/perception/activity_recognition/dependencies.ini
  src/opendr/perception/activity_recognition/utils/__init__.py
  src/opendr/perception/activity_recognition/utils/lightning.py
  src/opendr/perception/activity_recognition/x3d/algorithm/operators.py
  src/opendr/perception/activity_recognition/x3d/x3d_learner.py
  tests/sources/tools/perception/activity_recognition/cox3d/test_cox3d_learner.py
  tests/sources/tools/perception/activity_recognition/x3d/test_x3d_learner.py
Labels: test sources, test tools

#367 siamrpn: Single Object tracking 2d
  CHANGELOG.md
  docs/reference/index.md
  docs/reference/object-tracking-2d-siamrpn.md
  docs/reference/opendr-ros-bridge.md
  projects/opendr_ws/src/opendr_bridge/CMakeLists.txt
  projects/opendr_ws/src/opendr_bridge/src/opendr_bridge/bridge.py
  projects/opendr_ws/src/opendr_bridge/srv/OpenDRSingleObjectTracking.srv
  projects/opendr_ws/src/opendr_perception/CMakeLists.txt
  projects/opendr_ws/src/opendr_perception/README.md
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_2d_siamrpn_node.py
  projects/python/perception/object_tracking_2d/demos/siamrpn/README.md
  projects/python/perception/object_tracking_2d/demos/siamrpn/eval_demo.py
  projects/python/perception/object_tracking_2d/demos/siamrpn/inference_demo.py
  projects/python/perception/object_tracking_2d/demos/siamrpn/train_demo.py
  src/opendr/perception/object_detection_2d/datasets/detection_dataset.py
  src/opendr/perception/object_detection_2d/datasets/transforms.py
  src/opendr/perception/object_detection_2d/datasets/wider_person.py
  src/opendr/perception/object_detection_2d/ssd/ssd_learner.py
  src/opendr/perception/object_detection_2d/utils/vis_utils.py
  src/opendr/perception/object_detection_2d/yolov3/yolov3_learner.py
  src/opendr/perception/object_detection_2d/yolov5/yolov5_learner.py
  src/opendr/perception/object_tracking_2d/__init__.py
  src/opendr/perception/object_tracking_2d/datasets/__init__.py
  src/opendr/perception/object_tracking_2d/datasets/otb_dataset.py
  src/opendr/perception/object_tracking_2d/siamrpn/README.md
  src/opendr/perception/object_tracking_2d/siamrpn/__init__.py
  src/opendr/perception/object_tracking_2d/siamrpn/data_utils/__init__.py
  src/opendr/perception/object_tracking_2d/siamrpn/data_utils/otb.py
  src/opendr/perception/object_tracking_2d/siamrpn/siamrpn_learner.py
  tests/sources/tools/perception/object_detection_2d/yolov5/test_yolov5.py
  tests/sources/tools/perception/object_tracking_2d/siamrpn/__init__.py
  tests/sources/tools/perception/object_tracking_2d/siamrpn/test_siamrpn.py
  tests/test_license.py
Labels: enhancement, test sources, test tools

#378 SiamRPN fixes and ab3dmot ros1 node duplicate shortcut
  projects/opendr_ws/src/opendr_perception/CMakeLists.txt
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_2d_siamrpn_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_3d_ab3dmot_node.py
Labels: bug, test sources, test tools

#385 ROS1 readme additions
  projects/opendr_ws/README.md
  projects/opendr_ws/src/opendr_perception/README.md
Labels: documentation, test sources

#370 Continual ST-GCN
  CHANGELOG.md
  docs/reference/index.md
  docs/reference/skeleton-based-action-recognition.md
  projects/python/perception/skeleton_based_action_recognition/README.md
  projects/python/perception/skeleton_based_action_recognition/benchmark/README.md
  projects/python/perception/skeleton_based_action_recognition/benchmark/benchmark_costgcn.py
  projects/python/perception/skeleton_based_action_recognition/benchmark/install_on_server.sh
  projects/python/perception/skeleton_based_action_recognition/benchmark/requirements.txt
  projects/python/perception/skeleton_based_action_recognition/demos/costgcn_usage_demo.py
  src/opendr/perception/activity_recognition/cox3d/cox3d_learner.py
  src/opendr/perception/object_detection_2d/detr/detr_learner.py
  src/opendr/perception/object_detection_2d/gem/gem_learner.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/backbone/ghostnet.py
  src/opendr/perception/object_detection_2d/yolov5/yolov5_learner.py
  src/opendr/perception/skeleton_based_action_recognition/__init__.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/models/co_agcn.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/models/co_base.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/models/co_stgcn.py
  src/opendr/perception/skeleton_based_action_recognition/algorithm/models/co_str.py
  src/opendr/perception/skeleton_based_action_recognition/continual_stgcn_learner.py
  src/opendr/perception/skeleton_based_action_recognition/dependencies.ini
  tests/sources/tools/perception/object_detection_2d/yolov5/test_yolov5.py
  tests/sources/tools/perception/skeleton_based_action_recognition/test_costgcn.py
Labels: test sources, test tools

#264 Fer va estimation
  CHANGELOG.md
  __init__.py
  docs/reference/image_based_facial_emotion_estimation.md
  docs/reference/index.md
  projects/opendr_ws/README.md
  projects/opendr_ws/src/opendr_perception/CMakeLists.txt
  projects/opendr_ws/src/opendr_perception/README.md
  projects/opendr_ws/src/opendr_perception/scripts/facial_emotion_estimation_node.py
  projects/python/__init__.py
  projects/python/perception/__init__.py
  projects/python/perception/facial_expression_recognition/image_based_facial_emotion_estimation/README.md
  projects/python/perception/facial_expression_recognition/image_based_facial_emotion_estimation/benchmark_esr.py
  projects/python/perception/facial_expression_recognition/image_based_facial_emotion_estimation/face_detector/frontal_face.xml
  projects/python/perception/facial_expression_recognition/image_based_facial_emotion_estimation/inference_demo.py
  src/opendr/perception/facial_expression_recognition/__init__.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/README.md
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/__init__.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/algorithm/model/cbam.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/algorithm/model/diversified_esr.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/algorithm/model/esr_9.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/algorithm/utils/datasets.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/algorithm/utils/diversity.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/algorithm/utils/image_processing.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/algorithm/utils/plotting.py
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/dependencies.ini
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/facial_emotion_learner.py
  tests/sources/tools/perception/facial_expression_recognition/image_based_facial_emotion_estimation/__init__.py
  tests/sources/tools/perception/facial_expression_recognition/image_based_facial_emotion_estimation/test_esr.py
  tests/sources/tools/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/test_pstbln.py
  tests/test_license.py
Labels: test sources, test tools

#346 Image-based facial emotion estimation ROS2 node
  projects/opendr_ws_2/src/opendr_bridge/opendr_bridge/bridge.py
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/facial_emotion_estimation_node.py
  projects/opendr_ws_2/src/opendr_perception/setup.py
Labels: test sources

#377 Human model gen scikit fix
  projects/opendr_ws/src/opendr_simulation/README.md
  projects/opendr_ws/src/opendr_simulation/scripts/human_model_generation_client.py
  projects/opendr_ws/src/opendr_simulation/scripts/human_model_generation_service.py
Labels: test sources, test tools, test release

#384 Tx2 install dev
  Dockerfile-embedded
  bin/activate_nvidia.sh
  bin/install_nvidia.sh
  docs/reference/customize.md
  docs/reference/installation.md
  projects/opendr_ws/README.md
  projects/opendr_ws/src/opendr_perception/scripts/face_detection_retinaface_node.py
  projects/opendr_ws/src/opendr_perception/scripts/face_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/fall_detection_node.py
  projects/opendr_ws/src/opendr_perception/scripts/image_dataset_node.py
  projects/opendr_ws/src/opendr_perception/scripts/landmark_based_facial_expression_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_centernet_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_detr_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_gem_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_nanodet_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_ssd_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_yolov3_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_2d_yolov5_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_detection_3d_voxel_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_2d_deep_sort_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_2d_fair_mot_node.py
  projects/opendr_ws/src/opendr_perception/scripts/object_tracking_3d_ab3dmot_node.py
  projects/opendr_ws/src/opendr_perception/scripts/panoptic_segmentation_efficient_ps_node.py
  projects/opendr_ws/src/opendr_perception/scripts/point_cloud_dataset_node.py
  projects/opendr_ws/src/opendr_perception/scripts/pose_estimation_node.py
  projects/opendr_ws/src/opendr_perception/scripts/semantic_segmentation_bisenet_node.py
  projects/opendr_ws/src/opendr_perception/scripts/skeleton_based_action_recognition_node.py
  projects/opendr_ws/src/opendr_perception/scripts/video_activity_recognition_node.py
  projects/python/perception/activity_recognition/demos/online_recognition/demo.py
  src/opendr/engine/data.py
  src/opendr/perception/object_detection_2d/detr/algorithm/datasets/coco.py
  src/opendr/perception/object_detection_2d/detr/algorithm/datasets/panoptic_eval.py
  src/opendr/perception/object_detection_2d/detr/algorithm/engine.py
  src/opendr/perception/object_detection_2d/detr/algorithm/models/segmentation.py
  src/opendr/perception/object_detection_2d/detr/detr_learner.py
  src/opendr/perception/object_detection_2d/gem/algorithm/engine.py
  src/opendr/perception/object_detection_2d/gem/gem_learner.py
  src/opendr/perception/speech_recognition/edgespeechnets/edgespeechnets_learner.py
Labels: documentation, enhancement, test sources, test tools

#388 Changed git clone to develop branch
  Dockerfile-embedded
Labels: bug, test sources

#353 Improve workflows
  .github/workflows/test_packages.yml
  .github/workflows/tests_suite.yml
  .github/workflows/tests_suite_develop.yml
  .gitignore
  Dockerfile
  Dockerfile-cuda
  bin/build_wheel.sh
  bin/install.sh
  dependencies/pip_requirements.txt
  docs/reference/face-detection-2d-retinaface.md
  docs/reference/installation.md
  docs/reference/mobile-manipulation.md
  packages.txt
  projects/opendr_ws/src/opendr_bridge/package.xml
  projects/opendr_ws/src/opendr_data_generation/package.xml
  projects/opendr_ws/src/opendr_perception/package.xml
  projects/opendr_ws/src/opendr_simulation/package.xml
  projects/python/perception/slam/full_map_posterior_gmapping/src/fmp_slam_eval/package.xml
  projects/python/perception/slam/full_map_posterior_gmapping/src/map_simulator/package.xml
  src/c_api/dependencies.ini
  src/opendr/_setup.py
  src/opendr/_version.py
  src/opendr/control/mobile_manipulation/dependencies.ini
  src/opendr/control/mobile_manipulation/install_mobile_manipulation.sh
  src/opendr/control/single_demo_grasp/dependencies.ini
  src/opendr/control/single_demo_grasp/install_single_demo_grasp.sh
  src/opendr/engine/dependencies.ini
  src/opendr/perception/activity_recognition/dependencies.ini
  src/opendr/perception/compressive_learning/dependencies.ini
  src/opendr/perception/face_recognition/dependencies.ini
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/dependencies.ini
  src/opendr/perception/facial_expression_recognition/landmark_based_facial_expression_recognition/dependencies.ini
  src/opendr/perception/heart_anomaly_detection/dependencies.ini
  src/opendr/perception/multimodal_human_centric/audiovisual_emotion_learner/dependencies.ini
  src/opendr/perception/multimodal_human_centric/dependencies.ini
  src/opendr/perception/object_detection_2d/dependencies.ini
  src/opendr/perception/object_detection_2d/detr/dependencies.ini
  src/opendr/perception/object_detection_2d/gem/dependencies.ini
  src/opendr/perception/object_detection_2d/nanodet/dependencies.ini
  src/opendr/perception/object_detection_3d/voxel_object_detection_3d/dependencies.ini
  src/opendr/perception/object_tracking_2d/dependencies.ini
  src/opendr/perception/panoptic_segmentation/efficient_ps/dependencies.ini
  src/opendr/perception/pose_estimation/dependencies.ini
  src/opendr/perception/skeleton_based_action_recognition/dependencies.ini
  src/opendr/planning/end_to_end_planning/dependencies.ini
  src/opendr/simulation/human_model_generation/dependencies.ini
  tests/sources/tools/control/mobile_manipulation/run_ros.sh
  tests/sources/tools/perception/activity_recognition/x3d/test_x3d_learner.py
  tests/sources/tools/perception/object_detection_3d/voxel_object_detection_3d/test_object_detection_3d.py
  tests/sources/tools/perception/skeleton_based_action_recognition/costgcn/__init__.py
  tests/sources/tools/perception/skeleton_based_action_recognition/costgcn/test_costgcn.py
  tests/sources/tools/perception/skeleton_based_action_recognition/pstgcn/__init__.py
  tests/sources/tools/perception/skeleton_based_action_recognition/pstgcn/test_pstgcn.py
  tests/sources/tools/perception/skeleton_based_action_recognition/stbln/__init__.py
  tests/sources/tools/perception/skeleton_based_action_recognition/stbln/test_stbln.py
  tests/sources/tools/perception/skeleton_based_action_recognition/stgcn/__init__.py
  tests/sources/tools/perception/skeleton_based_action_recognition/stgcn/test_stgcn.py
  tests/sources/tools/perception/skeleton_based_action_recognition/tagcn/__init__.py
  tests/sources/tools/perception/skeleton_based_action_recognition/tagcn/test_tagcn.py
Labels: enhancement, test sources, test tools, test release
