Repository opendr-eu/opendr, pull requests merged in 2023-11, with the labels that each got.

#485 Synchronizes `develop` with `master`
  Dockerfile-cuda
  src/opendr/perception/activity_recognition/dependencies.ini
  src/opendr/perception/pose_estimation/hr_pose_estimation/high_resolution_learner.py
Labels: test sources, test tools

#482 Enhanced GPU installation from source (cloning)
  docs/reference/installation.md
Labels: documentation, test sources

#476 Finetuned yolov5 for trucks
  docs/reference/object-detection-2d-yolov5.md
  projects/python/perception/object_detection_2d/yolov5/inference_demo_agriculture_vehicles.py
  src/opendr/perception/object_detection_2d/yolov5/yolov5_learner.py
Labels: test sources, test tools

#487 Yolov5 trucks fixes
  docs/reference/object-detection-2d-yolov5.md
  src/opendr/perception/object_detection_2d/yolov5/yolov5_learner.py
Labels: documentation, test sources, test tools

#477 Fixed simulation to run with Webots R2023b
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/controllers/generate_robotti_obstacles_datasets/generate_robotti_obstacles_datasets.py
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/controllers/mavic2pro_patrol/mavic2pro_patrol.py
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/protos/CropPlant.proto
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/protos/Road.proto
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/protos/Robotti.proto
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/protos/RobottiCamera.proto
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/protos/textures/line_base_color_dashed.png
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/protos/textures/line_normal.jpg
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/protos/textures/line_occlusion.jpg
  projects/python/simulation/agricultural-simulation-dataset-generator/agricultural-environment-robotti-mavicpro/worlds/agricultural-environment-robotti-mavicpro.wbt
Labels: test sources

#483 Changed python dependencies installation
  dependencies/install.sh
  dependencies/parse_dependencies.py
  projects/python/perception/activity_recognition/benchmark/install_on_server.sh
  projects/python/perception/skeleton_based_action_recognition/benchmark/install_on_server.sh
  src/opendr/perception/activity_recognition/dependencies.ini
  src/opendr/perception/continual_slam/dependencies.ini
  src/opendr/perception/facial_expression_recognition/image_based_facial_emotion_estimation/dependencies.ini
  src/opendr/perception/gesture_recognition/dependencies.ini
  src/opendr/perception/skeleton_based_action_recognition/dependencies.ini
Labels: test sources, test tools

#479 Adaptive HR Pose Estimation
  docs/reference/high-resolution-pose-estimation.md
  projects/python/perception/pose_estimation/high_resolution_pose_estimation/README.md
  projects/python/perception/pose_estimation/high_resolution_pose_estimation/demos/benchmarking_demo.py
  projects/python/perception/pose_estimation/high_resolution_pose_estimation/demos/eval_demo.py
  projects/python/perception/pose_estimation/high_resolution_pose_estimation/demos/inference_demo.py
  projects/python/perception/pose_estimation/high_resolution_pose_estimation/demos/webcam_demo.py
  src/opendr/perception/pose_estimation/hr_pose_estimation/high_resolution_learner.py
  tests/sources/tools/perception/pose_estimation/high_resolution_pose_estimation/test_high_resolution_pose_estimation.py
Labels: test sources, test tools

#459 Active_demo and some minor bug fixes on FaceRecognition
  projects/opendr_ws/src/opendr_perception/CMakeLists.txt
  projects/opendr_ws/src/opendr_perception/README.md
  projects/opendr_ws/src/opendr_perception/scripts/active_face_recognition_node.py
  projects/python/perception/face_recognition/README.md
  projects/python/perception/face_recognition/demos/active_demo.py
  src/opendr/perception/face_recognition/face_recognition_learner.py
Labels: test sources, test tools

#490 Nanodet jit and c fixes
  docs/reference/c-object-detection-2d-nanodet-jit-h.md
  docs/reference/object-detection-2d-nanodet.md
  include/object_detection_2d_nanodet_jit.h
  projects/c_api/samples/object_detection_2d/nanodet/nanodet_jit_demo.c
  projects/python/perception/object_detection_2d/nanodet/README.md
  projects/python/perception/object_detection_2d/nanodet/export_c_compatible_network.py
  src/c_api/object_detection_2d_nanodet_jit.cpp
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/data/transform/warp.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/inferencer/utilities.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/arch/one_stage_detector.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/backbone/custom_csp.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/backbone/efficientnet_lite.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/backbone/ghostnet.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/backbone/resnet.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/fpn/fpn.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/fpn/ghost_pan.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/head/gfl_head.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/head/nanodet_plus_head.py
  src/opendr/perception/object_detection_2d/nanodet/algorithm/nanodet/model/module/conv.py
  src/opendr/perception/object_detection_2d/nanodet/nanodet_learner.py
  tests/sources/c_api/test_nanodet.c
Labels: test sources, test tools
