Repository opendr-eu/opendr, pull requests merged in 2023-10, with the labels that each got.

#469 Apply cuDNN init fix to all Object Detectors 2D
  projects/python/perception/object_detection_2d/yolov5/webcam_demo.py
  src/opendr/perception/object_detection_2d/__init__.py
Labels: bug, test sources, test tools

#467 New utility feature class filtering for Object Detectors 2D
  projects/python/perception/object_detection_2d/yolov5/filtered_inference_demo.py
  src/opendr/perception/object_detection_2d/utils/class_filter_wrapper.py
Labels: enhancement, test sources, test tools

#462 Adding prompt when transcribe with Whisper
  docs/reference/speech-transcription-vosk.md
  docs/reference/speech-transcription-whisper.md
  projects/opendr_ws/src/opendr_perception/README.md
  projects/opendr_ws/src/opendr_perception/scripts/speech_transcription_node.py
  projects/opendr_ws_2/src/opendr_perception/README.md
  projects/opendr_ws_2/src/opendr_perception/opendr_perception/speech_transcription_node.py
  projects/python/perception/speech_transcription/README.md
  projects/python/perception/speech_transcription/demo.py
  projects/python/perception/speech_transcription/demo_live.py
  src/opendr/perception/speech_transcription/whisper/whisper_learner.py
Labels: test sources, test tools

#471 Updated test_suite_develop.yml based on latest test_suite.yml
  .github/workflows/tests_suite_develop.yml
Labels: test sources
