Repository opendr-eu/opendr, pull requests merged in 2023-01, with the labels that each got.

#392 Lightweight OpenPose tool fixes and improvements
  docs/reference/lightweight-open-pose.md
  projects/python/perception/pose_estimation/lightweight_open_pose/README.md
  projects/python/perception/pose_estimation/lightweight_open_pose/demos/benchmarking_demo.py
  projects/python/perception/pose_estimation/lightweight_open_pose/demos/eval_demo.py
  projects/python/perception/pose_estimation/lightweight_open_pose/demos/inference_demo.py
  projects/python/perception/pose_estimation/lightweight_open_pose/demos/webcam_demo.py
  src/opendr/perception/pose_estimation/lightweight_open_pose/lightweight_open_pose_learner.py
Labels: documentation, test sources, test tools

#396 Add zenodo DOI badge
  README.md
Labels: test sources

#394 Wave detection demo based on pose estimation
  projects/python/perception/pose_estimation/lightweight_open_pose/README.md
  projects/python/perception/pose_estimation/lightweight_open_pose/demos/wave_detection_demo.py
  projects/python/perception/pose_estimation/lightweight_open_pose/demos/webcam_demo.py
Labels: enhancement, test sources, test tools

#401 Yolov5 training
  projects/python/perception/object_detection_2d/yolov5/README.md
  projects/python/perception/object_detection_2d/yolov5/convert_detection_dataset.py
  src/opendr/perception/object_detection_2d/yolov5/yolov5_learner.py
Labels: test sources, test tools
